services:
  my_api:
    build: .
    ports:
      - "8000:8000"
    expose:
      - 8080
    command: bash -c "cd server && python main.py"
    depends_on:
      my_db:
        condition: service_healthy
      redis:
        condition: service_healthy

  my_db:
    image: postgres:15.1-alpine
    restart: always
    env_file:
      - .env
    environment:
      POSTGRES_PASSWORD: "${DB_PASSWORD}"
    ports:
      - "5433:5433"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 10s
      timeout: 30s
      retries: 5
    volumes:
      - db_data:/var/lib/postgresql/data/

  redis:
    image: redis:latest
    command: redis-server
    restart: always
    ports:
      - "6379:6379"
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 10s
      timeout: 5s
      retries: 3
    volumes:
      - redis_data:/data


  adminer:
    image: adminer
    restart: always
    ports:
      - '8080:8080'
    depends_on:
      - my_db
      - redis


volumes:
  db_data:
  redis_data: